version: '2'

services:
# mongodb:
#   image: bitnami/mongodb:latest
#   ports:
#     - 27017:27017

  myapp:
#    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/express:latest
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/my_app_development
      - DBUSER
      - DBPW
      - ENVIRONMENT
    # depends_on:
    #   - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/app
